steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
  
  # Build React app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'REACT_APP_API_URL=https://fullstack-backend-HASH-uc.a.run.app/api'
      - 'REACT_APP_APP_NAME=Kelompok 12 E-commerce'
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY